# Generated by Django 4.2.4 on 2023-10-09 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_mydata_delete_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyData',
            new_name='SubmitData',
        ),
    ]
