# Generated by Django 4.2.4 on 2023-10-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_mydata_submitdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submitdata',
            old_name='Data1',
            new_name='LocData',
        ),
        migrations.RenameField(
            model_name='submitdata',
            old_name='Data2',
            new_name='MfmData',
        ),
        migrations.RemoveField(
            model_name='submitdata',
            name='Data3',
        ),
        migrations.RemoveField(
            model_name='submitdata',
            name='Data4',
        ),
        migrations.AddField(
            model_name='submitdata',
            name='AgeData',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='submitdata',
            name='BudgetData',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='submitdata',
            name='CompanionData',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='submitdata',
            name='MotiveData',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='submitdata',
            name='StyleValue1',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='submitdata',
            name='StyleValue2',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='submitdata',
            name='StyleValue3',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='submitdata',
            name='StyleValue4',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='submitdata',
            name='StyleValue5',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='submitdata',
            name='StyleValue6',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='submitdata',
            name='StyleValue7',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='submitdata',
            name='StyleValue8',
            field=models.IntegerField(default=4),
        ),
    ]
